# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 09 Feb 2009 15:32:20 +0100
*               @ALL          0
*               @user         8
