/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../MultihopOscilloscope.h.
 */

public class Constants  {
    public static final byte NREADINGS = 5;
    public static final short DEFAULT_INTERVAL = 1024;
}
